Library/Pages/LibrarianContent/Accept.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.LibrarianContent
{
    public class AcceptModel : PageModel
    {
        public Account Account { get; set; }
        public Book Book { get; set; }
        public string State { get; set; } = "";
        public ulong Penalty { get; set; } = 0;
        public bool Loss { get; set; } = false;
        public int Delay{get;set;}

        readonly private ILibrarianRepos repos;
        public AcceptModel(ILibrarianRepos librarianRepos)
        {
            repos = librarianRepos;
        }

        public void OnGet(int idBook, int idAccount)
        {
            repos.InitialAcceptBook(idBook, idAccount);
            Account = repos.GetAccount(idAccount);
            Book=repos.GetBook(idBook);
            Delay=repos.DeadlineOverdue(idAccount, idBook);
        }

        public IActionResult OnPost(int idBook, int idAccount, ulong penalty=0 , string state = "", bool loss=false)
        {
            repos.AcceptBook(idBook, idAccount, state,loss);
            if(penalty!=0)
            repos.ChargeFine(idAccount, penalty);
            return RedirectToPage("LibrarianMain");
        }
    }
}

Library/Pages/LibrarianContent/CreateBook.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.LibrarianContent
{
    public class CreateBookModel : PageModel
    {
        public Book Book { get; set; }
        readonly private ILibrarianRepos repos;
        IWebHostEnvironment appEnvironment;
        public CreateBookModel(ILibrarianRepos librarianRepos, IWebHostEnvironment _appEnvironment)
        {
            repos = librarianRepos;
            appEnvironment = _appEnvironment;
        }

        public void OnGet()
        {
            Book = new Book();
        }

        public async Task<IActionResult> OnPost(Book book,IFormFile uploadedImage)
        {
            Book newBook = book;
            if (uploadedImage != null)
            {
                string path = "/img/" + uploadedImage.FileName;
                using (var fileStream = new FileStream(appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedImage.CopyToAsync(fileStream);
                }
                newBook.ImagePath = uploadedImage.FileName;
            }
            repos.AddBook(newBook);
            return RedirectToPage("LibrarianMain");
        }
    }
}

Library/Pages/LibrarianContent/GiveBook.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.LibrarianContent
{
    public class GiveBookModel : PageModel
    {
        public Account Account { get; set; }
        public Book Book { get; set; }
        public int DaysBookint { get; set; }

        readonly private ILibrarianRepos repos;
        public GiveBookModel(ILibrarianRepos librarianRepos)
        {
            repos = librarianRepos;
        }

        public void OnGet(int idBook, int idAccount)
        {
            Account = repos.GetAccount(idAccount);
            Book = repos.GetBook(idBook);
        }


        public IActionResult OnPost(int idBook, int idAccount, int days = 0)
        {
            repos.GiveBook(idBook, idAccount, days);
            return RedirectToPage("LibrarianMain");
        }
    }
}

Library/Pages/LibrarianContent/PayFine.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.LibrarianContent
{
    public class PayFineModel : PageModel
    {
        public Account Account { get; set; } = new Account() { Id = 0, Name = "" };
        

        readonly private ILibrarianRepos repos;
        public PayFineModel(ILibrarianRepos librarianRepos)
        {
            repos = librarianRepos;
        }

        public void OnGet(int idAccount)
        {
            Account = repos.GetAccount(idAccount);
        }

        public IActionResult OnPost(int idAccount, ulong pay)
        {
            repos.PayOffFine(idAccount, pay);
            return RedirectToPage("LibrarianMain");
        }
    }
}

Library/Pages/LibrarianContent/Services/Novelties.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Library.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.LibrarianContent.Services
{
    public class NoveltiesModel : PageModel
    {
        [BindProperty]
        public bool[] BooksBools { get; set; }
        [BindProperty]
        public Book[] Books { get; set; }
        public List<string> Names { get; set; }

        readonly private ILibrarianRepos repos;
        readonly private INovelties novel;
        public NoveltiesModel(ILibrarianRepos librarianRepos, INovelties novelties)
        {
            repos = librarianRepos;
            novel = novelties;
        }

        public void OnGet()
        {
            Books = repos.AllBooks.ToArray();
            BooksBools = new bool[Books.Length];
            Names = new List<string>();
            foreach(Account account in repos.Users)
            {
                Names.Add(account.Name);
            }
        }

        public IActionResult OnPost(string name)
        {
            Books = repos.AllBooks.ToArray();
            Account account = repos.Users.Where(u => u.Name == name).First();
            if (account != null)
            { 
                List<Book> sendBooks = new List<Book>();
                if (Books.Length == BooksBools.Length)
                    for (int i = 0; i < Books.Length; i++)
                    {
                        if (BooksBools[i])
                        {
                            sendBooks.Add(Books[i]);
                        }
                    }
                novel.SendMessageAboutBooks(account, sendBooks.ToArray()); 
            }
            return RedirectToPage("../LibrarianMain");
        }
    }
}

Library/Pages/LibrarianContent/ValueHandler.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.LibrarianContent
{
    public class ValueHandlerModel : PageModel
    {
        readonly private ILibrarianRepos repos;
        IWebHostEnvironment appEnvironment;
        public ValueHandlerModel(ILibrarianRepos librarianRepos, IWebHostEnvironment _appEnvironment)
        {
            repos = librarianRepos;
            appEnvironment = _appEnvironment;
        }

        public void OnGet()
        {
        }

        public IActionResult OnGetRemoveBook(int idBook)
        {
            var book = repos.GetBook(idBook);
            FileInfo fileInfo = new FileInfo(appEnvironment.WebRootPath + "/img/"+book.ImagePath);
            fileInfo.Delete();
            repos.RemoveBook(idBook);
            return RedirectToPage("LibrarianMain");
        }
    }
}

Library/Pages/UserContent/ValueHandler.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Library.Pages.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.UserContent
{
    public class ValueHandlerModel : PageModel
    {
        readonly private IUserRepos repos;
        readonly private string url= "UserMain";
        public ValueHandlerModel(IUserRepos userRepos)
        {
            repos = userRepos;
        }
        public void OnGet()
        {
        }

   
        public IActionResult OnGetBusyBook(int idBook,int idAccount)
        {
            repos.BusyBook(idBook, idAccount);
            IdBookAccountViewModel bookAccountViewModel = new IdBookAccountViewModel(idBook, idAccount);
            return RedirectToPage("BookPage","Restart" , bookAccountViewModel);
        }

        public IActionResult OnGetTakeOff(int idBook, int idAccount)
        {
            repos.TakeOff(idBook);
            IdBookAccountViewModel bookAccountViewModel = new IdBookAccountViewModel(idBook, idAccount);
            return RedirectToPage("BookPage", "Restart", bookAccountViewModel);
        }

        public IActionResult OnGetMakeComment(Account account, int idBook, string textComment)
        {
            repos.MakeComment(account, idBook, textComment);
            IdBookAccountViewModel bookAccountViewModel = new IdBookAccountViewModel(idBook, account.Id);
            return RedirectToPage("BookPage", "Restart", bookAccountViewModel);
        }
        //public IActionResult OnGetMakeComment(CommentViewModel comment)
        //{
        //    repos.MakeComment(comment.CommentAccount, comment.IdBook, comment.TextComment);
        //    BookAccountViewModel bookAccountViewModel = new BookAccountViewModel(comment.IdBook, comment.CommentAccount.Id);
        //    return RedirectToPage("BookPage", "Restart", bookAccountViewModel);
        //}
    }
}

Library/Pages/LibrarianContent/Accept.cshtml
@page
@model Library.Pages.LibrarianContent.AcceptModel
@{
}
<div class="container">
    <main role="main" class="pb-3">
        <br />
        <div class="row">
            <div class="col-lg-2 col-md-2">
                <a asp-page="LibrarianMain" class="btn btn-warning">Назад</a>
            </div> 
            <div class="col-lg-5 col-md-5">
                <form method="post">
                    <input type="hidden" name="idAccount" asp-for="@Model.Account.Id" />
                    <input type="hidden" name="idBook" asp-for="@Model.Book.Id" />
                    <p>Сдача книги просрочена на: @Model.Delay дней</p>
                    <div class="form-group">
                        <label style="width:100%" asp-for="@Model.State">Опишите состояние книги. Пропустите пункт, если оно не изменилось.</label>
                        <textarea style="width:100%" asp-for="@Model.State" name="state"></textarea>
                    </div>
                    <div class="form-group">
                        <input class="form-check-input" style="width:100%" type="checkbox" name="loss" asp-for="@Model.Loss" />
                        <label class="form-check-label" style="width:100%" asp-for="@Model.Loss">Книга была потеряна</label>
                    </div>
                    <div class="form-group">
                        <label style="width:100%" asp-for="@Model.Penalty">Добавить штраф</label>
                        <input style="width:100%" type="number" name="penalty" asp-for="@Model.Penalty" />
                    </div>
                    <input class="btn btn-danger" value="Принять книгу" type="submit" />
                </form>
            </div>
            <div class="col-lg-5 col-md-5">
                <h3>@Model.Book.Title, Id: @Model.Book.Id</h3>
                <h4>(@Model.Book.Author)</h4>
                <p>Состояние книги перед сдачей: @Model.Book.State</p>
                <h3>Забронировал/а: @Model.Account.Name, Id: @Model.Account.Id</h3>
                <p>Забронировано книг: @Model.Account.BusyBooks</p>
                <p>Размер штрафа: @Model.Account.Penalty</p>
            </div>
        </div>
    </main>
</div>

Library/Pages/LibrarianContent/CreateBook.cshtml
@page
@model Library.Pages.LibrarianContent.CreateBookModel
@{
}
<div class="container">
    <main role="main" class="pb-3">
        <div class="row justify-content-start">
            <div class="col-lg-3 col-md-3">
                <br />
                <a asp-page="LibrarianMain" class="btn btn-warning">Назад</a>
            </div>
            <div class="col-lg-5 col-md-5">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label class="col-form-label" style="width:100%" asp-for="@Model.Book.Title">Введите название книги</label>
                        <input class="form-control" style="width:100%" asp-for="@Model.Book.Title" />
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" style="width:100%" asp-for="@Model.Book.Author">Автор</label>
                        <input class="form-control" style="width:100%" type="text"  asp-for="@Model.Book.Author" />
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" for="uploadedImage" style="width:100%">Загрузите фото обложки</label>
                        <input class="form-control-file btn badge-light" type="file" name="uploadedImage" />
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" style="width:100%" asp-for="@Model.Book.Genre">Жанр книги</label>
                        <input class="form-control" style="width:100%" type="text"  asp-for="@Model.Book.Genre" />
                    </div>
                    <div class="form-group">
                        <label style="width:100%" asp-for="@Model.Book.Publisher">Издатель</label>
                        <input class="form-control" style="width:100%" type="text"  asp-for="@Model.Book.Publisher" />
                    </div>
                    <div class="form-group">
                        <label style="width:100%" asp-for="@Model.Book.PublisherYear">Год издания</label>
                        <input class="form-control" style="width:100%" type="number"  asp-for="@Model.Book.PublisherYear" />
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" style="width:100%" asp-for="@Model.Book.State">Состояние</label>
                        <textarea class="form-control" style="width:100%" type="text"  asp-for="@Model.Book.State" ></textarea>
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" style="width:100%" asp-for="@Model.Book.Description">Описание книги</label>
                        <textarea class="form-control" style="width:100%" type="text"  asp-for="@Model.Book.Description" ></textarea>
                    </div>
                    <input class="btn btn-success" value="Создать" type="submit" />
                </form>
            </div>
        </div>
    </main>
</div>

Library/Pages/LibrarianContent/GiveBook.cshtml
@page
@model Library.Pages.LibrarianContent.GiveBookModel
@{
}
<div class="container">
    <main role="main" class="pb-3">
        <br />
        <div class="row justify-content-start">
            <div class="col-lg-3 col-md-3">
                <br />
                <a asp-page="LibrarianMain" class="btn btn-warning">Назад</a>
            </div>
            <div class="col-lg-6 col-md-6">
                <form method="post">
                    <input type="hidden" asp-for="@Model.Book.Id" name="idBook" />
                    <input type="hidden" asp-for="@Model.Account.Id" name="idAccount" />
                    <div class="form-group">
                        <label>Срок бронирования</label>
                        <input class="form-control" type="number" asp-for="@Model.DaysBookint" name="days" />
                    </div>
                    <div class="form-group">
                        <input class="btn btn-danger" type="submit" value="Отдать книгу" />
                    </div>
                </form>
            </div>
        </div>
    </main>
</div>

Library/Pages/LibrarianContent/LibrarianMain.cshtml
@page
@model Library.Pages.LibrarianContent.LibrarianMainModel
@{
//Layout = "_LibrarianLayout";
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">Library</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-page="LibrarianMain">Все книги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-page-handler="AllBusyBooks">Забронированные книги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-page-handler="GivenBooks">Отданные книги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-page-handler="FreeBooks">Свободные книги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-page-handler="ShowAccounts">Пользователи</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <a class="btn btn-info" asp-page="CreateBook" >Добавить книгу</a>
        <a class="btn btn-info" asp-page="Services/Novelties">Оповестить о новых книгах</a>
        <br /><br />
        <div class="row">
            @if (Model.ShowBooks)
            {
                foreach (Book book in Model.Books)
                {

                    Model.ChosenBook = book;
                    BookAccountObjViewModel bookAccount = new BookAccountObjViewModel(Model.ChosenBook, Model.ChosenAccount);
                    @Html.Partial("LookBook", bookAccount)

                }
            }
            else
            {
                foreach(Account account in Model.Accounts)
                {
                    @Html.Partial("LookAccount",account)
                }
            }
        </div>
    </main>
</div>

Library/Pages/LibrarianContent/LookAccount.cshtml
@model Account
    <div class="col-lg-3 col-md-3">
        <h3>@Model.Name, Id: @Model.Id</h3>
        <p>Почта: @Model.Email</p>
        <p>Штраф: @Model.Penalty</p>
        <p>Забронировано книг: @Model.BusyBooks</p>
        <p><a asp-page="PayFine" asp-route-idAccount="@Model.Id" class="btn btn-info">Погасить штраф</a></p>
    </div>

Library/Pages/LibrarianContent/LookBook.cshtml
@model BookAccountObjViewModel

@{

}
<div class="col-lg-3 col-md-3">
    <img class="img-thumbnail" src="~/img/@Model.BookObj.ImagePath" />
    <h3>@Model.BookObj.Title, Id: @Model.BookObj.Id</h3>
    <p>@Model.BookObj.Author</p>
    <p>Жанр: @Model.BookObj.Genre</p>
    <p>@Model.BookObj.ShortDescription</p>
    <br />
    @if (Model.BookObj.IsBusy)
    {

        @if (Model.BookObj.IsBorrow)
        {
            <p>Книгу забронировали и забрали</p>
            <a asp-page="Accept"  asp-route-idBook="@Model.BookObj.Id" asp-route-idAccount="@Model.AccountObj.Id" class="btn btn-success">Принять книгу</a>
        }
        else
        {
            <p>Книгу забронировали, но ещё не забрали</p>
            <a asp-page="GiveBook" asp-route-idBook="@Model.BookObj.Id" asp-route-idAccount="@Model.AccountObj.Id" class="btn btn-success">Отметить как отданную</a>
        }
        <br />
        <p>Забронировал: @Model.AccountObj.Name,Id: @Model.AccountObj.Id</p>
        <p>Забронировано книг: @Model.AccountObj.BusyBooks</p>
        <p>Размер штрафа: @Model.AccountObj.Penalty</p>
    }
    <p><a asp-page="ValueHandler" asp-page-handler="RemoveBook" asp-route-idBook="@Model.BookObj.Id" class="btn btn-danger">Удалить книгу</a></p>
</div>

Library/Pages/LibrarianContent/PayFine.cshtml
@page
@model Library.Pages.LibrarianContent.PayFineModel
@{
}
<div class="container">
    <main role="main" class="pb-3">
        <br />
        <div class="row justify-content-md-start">
            <div class="col-lg-3 col-md-3">
                <a asp-page="LibrarianMain" class="btn btn-warning">Назад</a>
            </div>
            <div class="col-lg-5 col-md-5">
                <form method="post">
                    <div class="form-group">
                        <h3 style="width:100%">@Model.Account.Name</h3>
                        <p>Размер штрафа составляет: @Model.Account.Penalty</p>
                    </div>
                    <div class="form-group">
                        <input type="hidden" asp-for="@Model.Account.Id" name="idAccount" />
                        <label style="width:100%" >Погасить штраф на</label>
                        <input style="width:100%" type="text" name="pay"/>
                    </div>
                    <input class="btn btn-info" type="submit" value="Погасить"/>
                </form>
            </div>
        </div>
    </main>
</div>

Library/Pages/LibrarianContent/ValueHandler.cshtml
@page
@model Library.Pages.LibrarianContent.ValueHandlerModel
@{
}

Library/Pages/LibrarianContent/_LibrarianLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Библиотекарь - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    @RenderBody()
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Library - <a asp-area="" asp-page="/Privacy">Авторские права</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>