Library/Pages/LibrarianContent/ValueHandler.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.LibrarianContent
{
    public class ValueHandlerModel : PageModel
    {
        readonly private ILibrarianRepos repos;
        IWebHostEnvironment appEnvironment;
        public ValueHandlerModel(ILibrarianRepos librarianRepos, IWebHostEnvironment _appEnvironment)
        {
            repos = librarianRepos;
            appEnvironment = _appEnvironment;
        }

        public void OnGet()
        {
        }

        public IActionResult OnGetRemoveBook(int idBook)
        {
            var book = repos.GetBook(idBook);
            FileInfo fileInfo = new FileInfo(appEnvironment.WebRootPath + "/img/"+book.ImagePath);
            fileInfo.Delete();
            repos.RemoveBook(idBook);
            return RedirectToPage("LibrarianMain");
        }
    }
}

Library/Pages/UserContent/ValueHandler.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Library.Pages.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.UserContent
{
    public class ValueHandlerModel : PageModel
    {
        readonly private IUserRepos repos;
        readonly private string url= "UserMain";
        public ValueHandlerModel(IUserRepos userRepos)
        {
            repos = userRepos;
        }
        public void OnGet()
        {
        }

   
        public IActionResult OnGetBusyBook(int idBook,int idAccount)
        {
            repos.BusyBook(idBook, idAccount);
            IdBookAccountViewModel bookAccountViewModel = new IdBookAccountViewModel(idBook, idAccount);
            return RedirectToPage("BookPage","Restart" , bookAccountViewModel);
        }

        public IActionResult OnGetTakeOff(int idBook, int idAccount)
        {
            repos.TakeOff(idBook);
            IdBookAccountViewModel bookAccountViewModel = new IdBookAccountViewModel(idBook, idAccount);
            return RedirectToPage("BookPage", "Restart", bookAccountViewModel);
        }

        public IActionResult OnGetMakeComment(Account account, int idBook, string textComment)
        {
            repos.MakeComment(account, idBook, textComment);
            IdBookAccountViewModel bookAccountViewModel = new IdBookAccountViewModel(idBook, account.Id);
            return RedirectToPage("BookPage", "Restart", bookAccountViewModel);
        }
        //public IActionResult OnGetMakeComment(CommentViewModel comment)
        //{
        //    repos.MakeComment(comment.CommentAccount, comment.IdBook, comment.TextComment);
        //    BookAccountViewModel bookAccountViewModel = new BookAccountViewModel(comment.IdBook, comment.CommentAccount.Id);
        //    return RedirectToPage("BookPage", "Restart", bookAccountViewModel);
        //}
    }
}

Library/Pages/UserContent/BookPage.cshtml
@page
@model Library.Pages.UserContent.BookPageModel
@{Layout = "_UserLayout";
}
<div class="container">
    <h2 class="text-center">@Model.UserBook.Title</h2>
    <div class="row justify-content-center">
        
        <div class="col-lg-5">
            <img class="img-thumbnail" src="~/img/@Model.UserBook.ImagePath" />
        </div>
        <div class="col-lg-5">
            <p>Автор: @Model.UserBook.Author</p>
            <p>Издатель: @Model.UserBook.Publisher</p>
            <p>Жанр: @Model.UserBook.Genre</p>
            <p>Год выпуска: @Model.UserBook.PublisherYear</p>
            <p>Состояние книги: @Model.UserBook.State</p>
            @if (Model.UserBook.IsBusy)
            {
                @if (Model.UserBook.IdAccount == Model.idAccount)
                {
                    <p>Забронировано вами</p>
                    <p><a asp-page="ValueHandler" asp-page-handler="TakeOff" asp-route-idBook="@Model.UserBook.Id" asp-route-idAccount="@Model.idAccount">Снять бронировку</a></p>
                }
                else
                {
                    <p>Забронировано на @Model.UserBook.BookingTime</p>
                }
            }
            else
            {
                <p>Доступно для бронирования</p>
                <a asp-page="ValueHandler" asp-page-handler="BusyBook" asp-route-idBook="@Model.UserBook.Id" asp-route-idAccount="@Model.idAccount">Забронировать книгу</a>
            }
            <h3>О книге:</h3>
            <p>@Model.UserBook.Description</p>
        </div>
        <div class="col-lg-10">
            <br />
            <br />
            <h2>Комментарии</h2>
            <form method="post">
                <input type="hidden" asp-for="@Model.UserAccount.Id" name="idAccount" />
                <input type="hidden" asp-for="@Model.UserAccount.Name" name="nameAccount" />
                <input type="hidden" asp-for="@Model.UserBook.Id" name="idBook" />
                <textarea name="textComment" asp-for="@Model.TextComment" type="text" style="width:100%;height:100px" placeholder="Оставьте комментарий"></textarea>
                <input class="btn btn-info" value="Отправить" type="submit" />
            </form>


            <hr />
            @foreach (Comment comment in Model.Comments)
            {
                <p>Имя: @comment.Name</p>
                <p>Дата и время комментария: @comment.Date</p>
                <p>@comment.TextComment</p>
                <br />
            }
        </div>
    </div>
</div>

Library/Pages/UserContent/LookBook.cshtml
@model DetailsViewModel

@{
    
}
<div class="col-lg-3 col-md-3">
    <img height="200" class="img-thumbnail" src="~/img/@Model.DetailBook.ImagePath" />
    <h3>@Model.DetailBook.Title</h3>
    <p>@Model.DetailBook.Author</p>
    <p>Жанр: @Model.DetailBook.Genre</p>
    <p>@Model.DetailBook.ShortDescription</p>
    <p><a asp-page="BookPage" asp-route-_idBook="@Model.DetailBook.Id" asp-route-_idAccount="@Model.DetailIdAccount" class="btn btn-success">Подробнее</a></p>
</div>

Library/Pages/UserContent/UserMain.cshtml
@page
@model Library.Pages.UserContent.UserMainModel

@{
    Layout = "_UserLayout";
}

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">Library</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <form class="form-inline row" method="post">
                <input type="hidden" class="form-control" name="idAccount" asp-for="@Model.IdAccount" />
                <div class=" form-group">
                    <label class="col-form-label" for="genre">
                        Жанр:
                        <select name="genre" class="form-control" asp-items="@new SelectList(Model.Genres)">
                        </select>
                    </label>
                </div> 
                <div class=" form-group">
                    <label>Автор:  </label>
                    <select name="author" class="form-control"  asp-items="@new SelectList(Model.Authors)">
                    </select>
                </div>
                <div class=" form-group">
                    <label>Издатель:  </label>
                    <select name="publisher" class="form-control" asp-items="@new SelectList(Model.Publishers)">
                    </select>
                </div>
                <div class=" form-group">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
                </div>
            </form>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <div class="row">
            @if (Model.Books != null)
                foreach (Book book in Model.Books)
                {
                    DetailsViewModel detailsViewModel = new DetailsViewModel(book, Model.IdAccount);
                    @Html.Partial("LookBook", detailsViewModel)


                }
        </div>
    </main>
</div>

Library/Pages/UserContent/ValueHandler.cshtml
@page
@model Library.Pages.UserContent.ValueHandlerModel
@{
}

Library/Pages/UserContent/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @RenderBody()
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Library - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>