Library/Pages/AdminContent/AdminMain.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.AdminContent
{
    public class AdminMainModel : PageModel
    {
        public List<Account> Accounts { get; set; }
        readonly private IAdminRepos repos;
        public AdminMainModel(IAdminRepos adminRepos)
        {
            repos = adminRepos;
        }

        public void OnGet()
        {
            Accounts = repos.Users.ToList();
        }

        public void OnGetSuperUsers()
        {
            Accounts = repos.SuperUsers.ToList();
        }

        public void OnGetDelete(int idAccount)
        {
            var account = repos.GetAccount(idAccount).Rights;
            repos.RemoveAccount(idAccount);
            if (account == "user")
                Accounts = repos.Users.ToList();
            else
                Accounts = repos.SuperUsers.ToList();
        }
    }
}

Library/Pages/AdminContent/CreateAccount.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Domain.Core;
using Library.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.AdminContent
{
    public class CreateAccountModel : PageModel
    {
        public Account NewAccount { get; set; } = new Account();
        readonly private IAdminRepos repos;
        public CreateAccountModel(IAdminRepos adminRepos)
        {
            repos=adminRepos;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost(Account account,string rights)
        {
            account.Rights = rights;
            repos.AddAccount(account);
            return RedirectToPage("AdminMain");
        }
    }
}

Library/Pages/AdminContent/AdminMain.cshtml
@page
@model Library.Pages.AdminContent.AdminMainModel
@{
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">Library</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-page="AdminMain">Обычные пользователи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-page-handler="SuperUsers">Супер пользователи</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <p>@TempData["error"]</p>
        <p><a class="btn btn-primary" asp-page="CreateAccount">Добавить аккаунт</a></p>
        <div class="row">
                @foreach (Account account in Model.Accounts)
                {
                    @Html.Partial("LookAccount", account)

                }
        </div>
    </main>
</div>

Library/Pages/AdminContent/ChangePassword.cshtml
@page
@model Library.Pages.AdminContent.ChangePasswordModel
@{
}
<div class="container">
    <main role="main" class="pb-3">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-5">
                <form method="post">
                    <input type="hidden" asp-for="@Model.ChangeAccount.Id" name="idAccount" />
                    <div class="form-group">
                        <label class="col-form-label" type="text" asp-for="@Model.ChangeAccount.Name">Имя пользователя</label>
                        <p>@Model.ChangeAccount.Name</p>
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" asp-for="@Model.ChangeAccount.Password">Пароль</label>
                        <input class="form-control" type="text" asp-for="@Model.ChangeAccount.Password" name="newPassword" />
                    </div>
                    <div class="form-group">
                        <label class="form-check-label" for="notify"> Оповестить об изменении пароля</label>
                        <input type="checkbox" asp-for="@Model.notify" name="notify" />
                    </div>
                    <input class="btn btn-danger" type="submit" value="Изменить" />
                </form>
                </div>
        </div>
    </main>
</div>

Library/Pages/AdminContent/CreateAccount.cshtml
@page
@model Library.Pages.AdminContent.CreateAccountModel
@{
}
<div class="container">
    <main role="main" class="pb-3">
        <br />
        <div class="row justify-content-start">
            <div class="col-lg-3 col-md-3">
                <a class="btn btn-warning" asp-page="AdminMain">Назад</a>
            </div>
            <div class="col-lg-5 col-md-5">
                <form method="post">
                    <div class="form-group">
                        <label class="col-form-label" type="text" asp-for="@Model.NewAccount.Name">Имя пользователя</label>
                        <input class="form-control" type="text" asp-for="@Model.NewAccount.Name" name="name" />
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" asp-for="@Model.NewAccount.Name">Электронная почта</label>
                        <input class="form-control" type="text" asp-for="@Model.NewAccount.Name" name="email" />
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" asp-for="@Model.NewAccount.Name">Пароль</label>
                         <input class="form-control" type="text" asp-for="@Model.NewAccount.Name" name="password" />
                    </div>
                    <div class="form-group">
                        <label class="col-form-label" asp-for="@Model.NewAccount.Rights">Права пользователя</label>
                        <select class="form-control-range" name="rights" type="text" asp-for="@Model.NewAccount.Rights">
                            <option value="user">Обычный пользователь</option>
                            <option value="admin">Администратор</option>
                            <option value="librarian">Библиотекарь</option>
                        </select>
                    </div>
                    <input class="btn btn-danger" type="submit" value="Создать" />
                </form>
                </div>
        </div>
    </main>
</div>

Library/Pages/AdminContent/LookAccount.cshtml
@model Account
<div class="col-lg-3 col-md-3">
    <h3>@Model.Name, Id: @Model.Id</h3>
    @if (Model.Rights == "user")
    {
        <p>Пользователь</p>
    }
    @if (Model.Rights == "librarian")
    {
        <p>Библиотекарь</p>
    }
    @if (Model.Rights == "admin")
    {
        <p>Администратор</p>
    }
    <p>Почта: @Model.Email</p>
    <p>Пароль: @Model.Password</p>
    <p>Штраф: @Model.Penalty</p>
    <p>Забронировано книг: @Model.BusyBooks</p>
    <p><a asp-page="ChangePassword" asp-route-idAccount="@Model.Id">Изменить пароль</a></p>
    <p><a asp-page-handler="Delete" asp-route-idAccount="@Model.Id" class="btn btn-danger">Удалить аккаунт</a></p>
</div>

Library/Pages/AdminContent/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Администратор - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    @RenderBody()
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Library - <a asp-area="" asp-page="/Privacy">Авторские права</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>